# Generated by Django 4.2.3 on 2023-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authors_genres_publishers_remove_books_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
