# Generated by Django 4.2.3 on 2023-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_genres_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='founding',
            field=models.DateField(blank=True, null=True),
        ),
    ]
