# Generated by Django 4.2.3 on 2023-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_publishers_founding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='book_list', to='books.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='book_list', to='books.genres'),
        ),
    ]
