# Generated by Django 4.2.3 on 2023-08-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_author_alter_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books_authored', to='books.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_published', to='books.publishers'),
        ),
    ]
