# Generated by Django 4.2.3 on 2023-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_author_alter_books_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ManyToManyField(related_name='books_published', to='books.publishers'),
        ),
    ]
