# Generated by Django 4.2.3 on 2023-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_books_publisher_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
